name: olearis
description: "A Flutter application with Clean Architecture."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Navigation
  go_router: ^14.8.1

  # Serialization
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  drift: ^2.28.2
  drift_flutter: ^0.2.7
  path_provider: ^2.1.5
  sqlite3_flutter_libs: ^0.5.41

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  freezed: ^2.5.7
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.4
  drift_dev: ^2.28.0

flutter:
  uses-material-design: true
  assets:
    - assets/